config/routes.rb
GameApp::Application.routes.draw do

  resources :geeks do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :plays, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

  root :to => 'static_pages#home'

  match '/signin', :to=> 'sessions#new'
  match '/signout', :to=> 'sessions#destroy', :via => :delete
  match '/signup', :to=> 'geeks#new'
  match '/help', :to=> 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to=> 'static_pages#contact'
  

end

app/models/geek.rb
# == Schema Information
#
# Table name: geeks
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  game_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Geek < ActiveRecord::Base
  attr_accessible :email, :game_id, :name, :password, :password_confirmation
  has_secure_password
  VALID_EMAIL_REGEX =   /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :presence=> true, :length => {:maximum => 30}
  validates :email, :presence=> true, :format=> { :with=> VALID_EMAIL_REGEX } ,
              :uniqueness => true
  before_save {|geek| geek.email = email.downcase }
  before_save :create_remember_token
  validates :password, :presence => true, :length => {:minimum => 6}
  validates :password_confirmation, :presence => true
  has_many :plays, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def feed
     Play.from_users_followed_by(self)
  end

  def following?(other_geek)
    relationships.find_by_followed_id(other_geek.id)
  end

  def follow!(other_geek)
    relationships.create!(followed_id: other_geek.id)
  end

  def unfollow!(other_geek)
    relationships.find_by_followed_id(other_geek.id).destroy
  end

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/models/play.rb
class Play < ActiveRecord::Base
  attr_accessible :comment, :content
  validates :geek_id, presence: true
  validates :comment, :length=> {:maximum => 140}
  validates :content, :length=> { :minimum=>3}
  belongs_to :geek
  default_scope order: 'plays.created_at DESC'
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :geek_id"
    where("geek_id IN (#{followed_user_ids}) OR geek_id = :geek_id",
          geek_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, class_name: "Geek"
  belongs_to :followed, class_name: "Geek"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/geeks_controller.rb
class GeeksController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy

  def new
    @user = Geek.new
  end

  def index
    @users = Geek.all.paginate(page: params[:page])
  end

  def show
    @user = Geek.find(params[:id])
    @plays = @user.plays.paginate(page: params[:page])
  end

  def create
    @user = Geek.new(params[:geek])
    if @user.save
      sign_in @user
      flash[:success]="Welcome to GameApp"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit

  end

  def update

    if @user.update_attributes(params[:geek])
      flash[:success] = "Profile Updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    Geek.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to geeks_path
  end

  def following
    @title = "Following"
    @user = Geek.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = Geek.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def correct_user
      @user = Geek.find(params[:id])
      if !current_user?(@user)
        redirect_to(root_path)
      end
    end

    def admin_user
      if !current_user.admin?
        redirect_to root_path
      end
    end

end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_filter :signed_in_user
  before_filter :correct_user, only: [:destroy]

  def create
    @play = current_user.plays.build(params[:play])
    if @play.save
      flash[:success] = "Well played"

    else
      flash[:notice] = "You shall not pass"
    end
    redirect_to root_path
  end

  def destroy
     @play.destroy
     redirect_to root_path
  end

  private
    def correct_user
      @play = current_user.plays.find_by_id(params[:id])
      if @play.nil?
        redirect_to root_path
      end
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :signed_in_user

  def create
    @user = Geek.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]) .followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
   geek = Geek.find_by_email(params[:session][:email].downcase)
    if geek && geek.authenticate(params[:session][:password])
      sign_in(geek)
      redirect_back_or geek
    else
      flash.now[:error] = "Invalid User/Password info"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @play = current_user.plays.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "ruby on rails"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/geeks_helper.rb
module GeeksHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(geek, size)
    gravatar_id = Digest::MD5::hexdigest(geek.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: geek.name, class: "gravatar", :height => "#{size}")
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(geek)
    cookies.permanent[:remember_token] = geek.remember_token
    self.current_user = geek
  end

  def current_user=(geek)
    @current_user = geek
  end

  def current_user
    @current_user ||= Geek.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(geek)
    geek == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    if !signed_in?
      store_location
      flash[:notice] = "Please sign in."
      redirect_to signin_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/geeks/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote:true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/geeks/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/geeks/_geek.html.erb
<li>
  <%= gravatar_for geek, 60 %>
  <%= link_to geek.name, geek %>
  <% if current_user.admin? && !current_user?(geek) %>
      | <%= link_to "delete", geek, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/geeks/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/geeks/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f|%>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email  %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user, 50 %>
        <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/geeks/index.html.erb
<% provide(:title, "All users") %>

<h1>All users</h1>
<%= will_paginate @users %>
<ul class="users">
  <li>
    <%= render @users %>
  </li>
</ul>
<%= will_paginate @users %>

app/views/geeks/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
     <% end %>
   </div>
</div>

app/views/geeks/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user,70 %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    <% if @user.plays.any? %>
        <h3>What have I played.. (<%= @user.plays.count %>)</h3>
        <ol class="plays">
          <%= render @plays %>
        </ol>
        <%= will_paginate @plays %>
    <% end %>
  </div>
</div>

app/views/geeks/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user,70 %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Plays:</b> <%= @user.plays.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <%= link_to gravatar_for(user, 40), user %>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users%>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', :id=> "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Users", geeks_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", geek_path(current_user) %></li>
                  <li><%= link_to "Settings", edit_geek_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%=  link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
           <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
           <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%=  render 'layouts/shim' %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <%end%>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/plays/_play.html.erb
<li>
  <span class="content"><%= play.content %></span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(play.created_at) %> ago.
  </span>
  <% if current_user?(play.geek) %>
      <%= link_to "delete", play, method: :delete,
                  data: { confirm: "You sure?" },
                  title: play.content %>
  <% end %>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('geeks/unfollow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('geeks/follow')) %>")
$("#followers").html('<%= @user.followers.count %>')

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="plays">
      <%= render partial: 'shared/feed_item', collection: @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.geek, 50), feed_item.geek %>
  <span class="user">
    <%= link_to feed_item.geek.name, feed_item.geek %>
  </span>
  <br/>
  <span class="content"><%= feed_item.content %></span>
  <br/>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.geek) %>
      <%= link_to "delete", feed_item, method: :delete,
                  data: { confirm: "You sure?" },
                  title: feed_item.content %>
      <% end %>
</li>

app/views/shared/_play_form.html.erb
<%= form_for(@play) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Have fun...", rows: "10" %>
    </div>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_geek_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_geek_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= geek_path(current_user) %>">
  <%= gravatar_for current_user, 70 %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.plays.count, "Stuff") %> to play with
</span>

app/views/static_pages/about.erb
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>
 <%= yield(:winfo) %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<%= full_title(yield(:title)) %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
    <div class="row">
      <aside class="span4">
        <section>
          <%= render 'shared/user_info' %>
        </section>
        <section>
          <%= render 'shared/stats' %>
        </section>
        <section>
          <%= render 'shared/play_form' %>
        </section>
      </aside>
      <div class = "span8" >
        <h3>My place, my rules!</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
<% else %>
    <div class="center hero-unit">
      <h1>Welcome to the Sample App</h1>

      <h2>
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>

      <%= link_to "Sign up now!", signup_path,
                  class: "btn btn-large btn-primary" %>
    </div>

    <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %> 